% This function loads a file generated by the UI team, and creates a city out of it.
% (First we need example cities from the UI team.)

function [c] = load_city(filename)


% Too bad csvload won't work.
% We will have to use textscan...

c = generate_city(10, 2, 2, 2);


end